baseURL = "https://galgame.us/"
languageCode = "zh-CN"
title = "ğ™‚ğ™–ğ™¡ğ™œğ™–ğ™¢ğ™š ğ™‹ğ™¤ğ™ğ™£ğ™© ğ™ªğ™¨"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
publishDir = "public"        # Site static file save directory

[params]
author = "weekend-project"
description = "ğ™‚ğ™–ğ™¡ğ™œğ™–ğ™¢ğ™š ğ™‹ğ™¤ğ™ğ™£ğ™© ğ™ªğ™¨"
upload = "https://blog.sct.moe/archives/ACGN-Start" # "Website Submission" in the left navigation bar
about = "/about"                                                        # "About Navigation" page on the left navigation bar (./about)
repository = "https://github.com/weekend-project-space/e9x-fun"
enablePreLoad = true                                                    # Preload animation before the website fully opens
textPreLoad = "ğ™‚ğ™–ğ™¡ğ™œğ™–ğ™¢ğ™š ğ™‹ğ™¤ğ™ğ™£ğ™© ğ™ªğ™¨"                                                     # Text of the preload animation, effective only when enablePreLoad=true
expandSidebar = false                                                   # Default expand left side navigation bar
logosPath = "assets/images/logos"                                       # Navigation address logo storage address of the website
defaultLogo = "/assets/images/404.png"                        # Default logo displayed when logo image resource does not exist or error; If this parameter is empty, the corresponding logo will continue to be loaded until successful
nightMode = false                                                       # Default site is in dark (night) mode
yiyan = false                                                            # Enable Yan service by default

[params.seo]
baiduhmid = '69748c135beab0a8530e9c8397f68d24' # Baidu statistics hm.src ID
## baiduSiteVer    = 'codeva-cCAOSG8MBO'			# Baidu HTML tag verification (baidu-site-verification)
tj51laid = ''        # 51.LA website statistics
tj51lack = ''
GoogleAdsClient = '' # Google AdSense 

[params.qweather]
key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
favicon = "/assets/images/404.ico"
searchImageL = "/assets/images/bg.jpg"        # Light background image of the search section
searchImageD = "/assets/images/bg.jpg"        # Dark background image of the search section
logoExpandLight = "/assets/images/404.png"
logoExpandDark = "/assets/images/404.png"
logoCollapseLight = "/assets/images/404.png"
logoCollapseDark = "/assets/images/404.png"

[markup.goldmark.renderer]
unsafe = true

[params.footer]
link = { text = "èŒICPå¤‡20249088å·", url = "https://icp.gov.moe/?keyword=20249088", target = "_blank" } # Verify if there are any TOML syntax errors and correct them
searchImageD = "/assets/images/bg.jpg"        # æœç´¢éƒ¨åˆ†æ·±è‰²èƒŒæ™¯å›¾
logoExpandLight = "/assets/images/404.png"
logoExpandDark = "/assets/images/404.png"
logoCollapseLight = "/assets/images/404.png"
logoCollapseDark = "/assets/images/404.png"

[markup.goldmark.renderer]
unsafe = true

[params.footer]
link = { text = "èŒICPå¤‡20249088å·", url = "https://icp.gov.moe/?keyword=20249088", target = "_blank" }
