baseURL = "https://galgame.us/"
languageCode = "zh-CN"
title = "ğ™‚ğ™–ğ™¡ğ™œğ™–ğ™¢ğ™š ğ™‹ğ™¤ğ™ğ™£ğ™© ğ™ªğ™¨"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
publishDir = "public"        # ç«™ç‚¹é™æ€æ–‡ä»¶ä¿å­˜ç›®å½•


[params]
author = "weekend-project"
description = "ğ™‚ğ™–ğ™¡ğ™œğ™–ğ™¢ğ™š ğ™‹ğ™¤ğ™ğ™£ğ™© ğ™ªğ™¨"
upload = "https://blog.sct.moe/archives/ACGN-Start" # å·¦ä¾§å¯¼èˆªæ çš„"ç½‘ç«™æäº¤"
about = "/about"                                                        # å·¦ä¾§å¯¼èˆªæ çš„"å…³äºå¯¼èˆª"é¡µé¢(./about)
repository = "https://github.com/weekend-project-space/e9x-fun"
enablePreLoad = true                                                    # ç½‘ç«™å®Œå…¨æ‰“å¼€å‰é¢„åŠ è½½åŠ¨ç”»
textPreLoad = "ğ™‚ğ™–ğ™¡ğ™œğ™–ğ™¢ğ™š ğ™‹ğ™¤ğ™ğ™£ğ™© ğ™ªğ™¨"                                                     # é¢„åŠ è½½çš„åŠ¨ç”»æ–‡å­—, åªæœ‰å½“enablePreLoad=trueæ—¶ç”Ÿæ•ˆ
expandSidebar = false                                                   # é»˜è®¤å±•å¼€å·¦ä¾§è¾¹å¯¼èˆªæ 
logosPath = "assets/images/logos"                                       # ç½‘ç«™æ¯ä¸ªå¯¼èˆªåœ°å€logoå­˜æ”¾åœ°å€
defaultLogo = "/assets/images/404.png"                        # logoå›¾ç‰‡èµ„æºä¸å­˜åœ¨æˆ–è€…é”™è¯¯æ—¶, é»˜è®¤æ˜¾ç¤ºçš„logo; è¯¥å‚æ•°å¦‚ä¸ºç©º,å°†ä¼šä¸€ç›´åŠ è½½å¯¹åº”çš„logo,ç›´è‡³æˆåŠŸ
nightMode = false                                                       # é»˜è®¤ç«™ç‚¹ä¸ºæ·±è‰²(å¤œé—´)æ¨¡å¼
yiyan = false                                                            # é»˜è®¤å¯ç”¨ä¸€è¨€æœåŠ¡

[params.seo]
baiduhmid = '69748c135beab0a8530e9c8397f68d24' # ç™¾åº¦ç»Ÿè®¡ hm.src çš„ ID
## baiduSiteVer    = 'codeva-cCAOSG8MBO'			# ç™¾åº¦HTMLæ ‡ç­¾éªŒè¯(baidu-site-verification)
tj51laid = ''        # 51.LA ç½‘ç«™ç»Ÿè®¡
tj51lack = ''
GoogleAdsClient = '' # Google AdSense 

[params.qweather]
key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
favicon = "/assets/images/404.ico"
searchImageL = "/assets/images/bg.jpg"        # æœç´¢éƒ¨åˆ†æµ…è‰²èƒŒæ™¯å›¾
searchImageD = "/assets/images/bg.jpg"        # æœç´¢éƒ¨åˆ†æ·±è‰²èƒŒæ™¯å›¾
logoExpandLight = "/assets/images/404.png"
logoExpandDark = "/assets/images/404.png"
logoCollapseLight = "/assets/images/404.png"
logoCollapseDark = "/assets/images/404.png"

[markup.goldmark.renderer]
unsafe = true

[params.footer]
copyright = <a href="https://icp.gov.moe/?keyword=20249088" target="_blank">èŒICPå¤‡20249088å·</a>
